###############################################################
##       ODDS RATIO siNIPBL vs WT peaks 
##  
##  Load peaks annotated with 18 chromatin states generated by
##  "peaks_siNIPBL_18states_TADs_annotation.R"
###############################################################

library(tidyverse)
options(dplyr.width=Inf)

wd <- "/Users/aqo/Desktop/cluster/MCF10A/OddsRatio-DEGs-CHMMstates"

## Load the peaks annotated with states and tads
loadDir <- "/Users/aqo/Desktop/cluster/MCF10A/siNipbl/Peaks/merged_replicates_callpeak/unique"
loadPath <- file.path(loadDir, "uniquePeaks_siNIPBL_intersected_18states_TADS@peakStatesTAD.RData")
load(loadPath)


## Load Chromatin States
STATEANNO <- "/Users/aqo/Desktop/cluster/MCF10A/siNipbl/log2ratio_CHRMMstates/state_annotations_byHand.txt"

chmm_states_anno <- read.table(STATEANNO, 
	header=FALSE, sep="\t") %>% 
	`names<-`(c("state","anno", "rgb")) %>%
	as_tibble()

## Create relational table using names (samples) form loaded data
config <- names(peakStatesTAD) %>%
	data.frame() %>% 
	`colnames<-`(c("sample")) %>%
	mutate(temp=sample) %>%
	separate(temp, sep = "_", into = c("Prot", "Condition", "OnlyIn", "siRNA"))

test_peaksBind <- bind_sameProt(config, "SA1", peakStatesTAD)
head(peakStatesTAD)
peakStatesTAD[grep("SA1", names(peakStatesTAD))] %>% do.call("nrow", .)
## I have to rbind Tibbles from the same Protein and add "class" column
## to identify gain or lost peaks
Config <- config
Protein <- "SA1"
PeaksList <- peakStatesTAD

## Modify bind_sameProt to work when selecting more than one elemnt from
## Peaks list
bind_sameProt <- function(Config, Protein, PeaksList) {
	samples <- Config$sample[Config$Prot == Protein]

	control <- samples[grep("Cont", samples)]
	treat <- samples[grep("Treat", samples)]

	control <- PeaksList[control] %>%
		do.call("rbind", .) %>%
		dplyr::mutate(class="lost")
	

	treat <- PeaksList[treat] %>%
		do.call("rbind", .) %>%
		dplyr::mutate(class="gain")

	res <- rbind(control, treat)

	return(res)
}

test_peaksBind <- bind_sameProt(config, "SA1", peakStatesTAD)
head(test_peaksBind)
table(test_peaksBind$exp)

State <- "CTCF"
PeaksState_tb <- test_peaksBind
Class <- "gain"

## Tablulate the number of gained/lost peaks per state.
## use grepl to select gained or lost
table_classINstate <- function(State, PeaksState_tb, Class=c("gain","lost")){

	## Combine kept peaks with the Class not used
	valid_classes <- c("gain","lost")
	other_class <- valid_classes[!grepl(Class, valid_classes)]

	ix <- grepl(Class, PeaksState_tb$class)
	
	PeaksState_tb$class[!ix] <- other_class

	inState <- PeaksState_tb$class[PeaksState_tb$anno == State] %>% table %>% as.vector
	noState <- PeaksState_tb$class[PeaksState_tb$anno != State] %>% table %>% as.vector

	dnms <- list(c("in", "out"), c("gained", "lost")) %>% `names<-`(c(State, "Peak"))
	
	## Make sure we are generating a 2x2 table or return -1 
	if ( length(inState) == 2 && length(noState) == 2 ) {
		mat <- matrix(c(inState, noState), ncol=2, byrow= TRUE, dimnames= dnms)
		
		return(mat)
	} else {
		return( -1 )
	}

}

OddsRatio_exact <- function(Table_2way) {

	or <- exact2x2::exact2x2(Table_2way, tsmethod="minlike")

	OR <- or$estimate [[1]]
	lower_CI <- or$conf.int[1] 
	upper_CI <- or$conf.int[2]
	pval <- or$p.value[[1]]

	return( list( estimates = c("OR" = OR,
							 "lower" = lower_CI,
							 "upper" = upper_CI,
							 "p.val" = pval),
				  data=or
				)
		  )
}

OR_state <- function(Config, Protein, PeaksList, State, Class) {
	peaks_same_prot <- bind_sameProt(Config, Protein, PeaksList)

	table_2x2 <- table_classINstate(State, peaks_same_prot, Class)

	if ( table_2x2 != -1 ) {
		or <- OddsRatio_exact(table_2x2)

		res <- data.frame(state= State,
						  class= Class,
						  protein= Protein,
						  OR= or$estimates['OR'],
						  lower= or$estimates['lower'],
						  upper= or$estimates['upper'],
						  p.val= or$estimates['p.val'])
	} else {
		res <- data.frame(state= State,
						  class= Class,
						  protein= Protein,
						  OR= -1,
						  lower= -1,
						  upper= -1,
						  p.val= -1)
	}
	return(res)
}

##Compute OR and plot
res <- data.frame()
for (state in chmm_states_anno$anno) {
	for (protein in c("SA1", "SA2", "SMC1")) {
		for (class in c("gain")) {
			cat(paste(protein, state, class, sep=" "), "\n")
			OR <- OR_state(config, protein, peakStatesTAD, state, class)
			res <- rbind(res, OR)
		}
	}
}

## ============ PLOT ============ ##
#To round xticks
scaleFUN <- function(x) signif(x, 2 )

## To add rectangles with colors for each state
char_toRGB <- function(rgb_str) {
	sapply(strsplit(rgb_str, ","), function(x) rgb(x[1], x[2], x[3], maxColorValue = 255)
)}

color <- chmm_states_anno %>% dplyr::mutate(color= char_toRGB(rgb)) %>%
	dplyr::select(state, anno, color) %>%
	rename(stateNumber="state") %>%
	dplyr::mutate(anno_toGG=gsub("_"," ", anno))

data <- dplyr::filter(res, OR != -1) %>%
	dplyr::mutate(signif= ifelse(p.val <= 0.05, "yes", "no")) %>%
	dplyr::inner_join(., color, by=c("state"="anno"))  %>%
	dplyr::mutate_at("state", as.factor) %>%
	dplyr::mutate_at(c("OR","lower","upper"), log2) %>%
	dplyr::mutate(OR_geomText=ifelse(p.val <= 0.05, OR, NA),
								state=gsub("_"," ", state))

## Filter class == "gain", because class == "lost" is OR WT/siNIPBL. 2 sides of the same coin.
ggplot(data=dplyr::filter(data, class=="gain"), 
	   mapping=aes(x=OR, y=state)) +
    geom_vline(aes(xintercept = 0), size = .25, linetype = "dashed") +
    facet_grid(~protein, scales="free") +
    scale_x_continuous(labels= scaleFUN,
    				   lim= c(-4, 4)) +
    scale_y_discrete(breaks= color$anno_toGG[order(color$stateNumber)] %>% rev,
    				 limits= color$anno_toGG[order(color$stateNumber)] %>% rev
    				 ) +
    geom_tile(aes(fill=state, x= -3), width= 1.5, height= 0.4, alpha = 0.6) +
    scale_fill_manual(limits=data$state,
			values=data$color) +
    guides(fill = "none") +
    geom_errorbarh(aes(xmax=upper, xmin=lower), size=0.4, 
      height = 0.2, color = "black")+ 
    geom_point(aes(x=OR, y=state, color=signif), shape=18, size=3 ) +
    scale_color_manual(
      values=c("orange","grey79"), 
      limits=c("yes", "no"),
      name="p-value <= 0.05") +
    geom_text(aes(x=OR, label=round(OR_geomText,2)), 
      size=3, position=position_nudge(y=.3, x=.3)) +
    theme_bw() +
    theme(panel.grid.minor = element_blank()) +
    ylab('') +
    xlab('Log2 Odds Ratio') +
    ggtitle('Odds Ratio siNIPBL vs WT peaks') +
    theme(plot.title=element_text(hjust=0.5),
    	axis.text.x=element_text(
    		size=rel(1.2),
				angle=30, hjust=0.5, vjust= 0.5,
				color= "black"),
    	axis.text.y=element_text(
    		size=rel(1.4),
    		color= "black"),	
	    	panel.grid.major= element_blank(),
	    	strip.background = element_rect(
				fill="black"
			),
    	strip.text = element_text(
    		face= "bold", color= "white"
    		)
    	)
plotPath <- file.path(wd, "OR_siNIPBLpeaks_vs_WTpeaks.pdf")
ggsave(plotPath,  width= 7.5, height = 5.5)

