###############################################################
####						        TAD CENTRE 				  							 ####
##
## The files generated by "intersect_TADs.sh" are the starting point
###############################################################


library(tidyverse)

wd <- "/Users/aqo/Desktop/cluster/MCF10A/siNipbl-siSA_combined/log2ratio_siNipbl_siSA_ChIPs_newPseudocount/TAD_borders"
resdir <- file.path(wd, "plots")
dir.create(resdir, showWarnings=FALSE)

setwd(resdir)

peaksDir <- wd


l <- list.files(peaksDir, pattern = "INTERSECT_TADmiddle.bed",
 full.names = FALSE)
l

## Compute distance to tad centre relative to TAD length 
l_dist <- lapply(l, function(x){
	f <- file.path(peaksDir, x)
	tad=read.table(f, sep="\t", header=FALSE, stringsAsFactors = FALSE) %>% 
		as_tibble() %>%
		select(-V6) %>%
		`colnames<-`(c("chr","start","end", "group","state",
			"TADstart","TADend","ID","TADmiddle","TADlength"))

	tad <- tad %>% mutate(absToMid=abs(TADmiddle-start)) %>%
		mutate(RelToMid=(absToMid/(0.5*TADlength)))

	return(tad)
})

names(l_dist)<-l

## toGG is the data frame which will be passed to ggplot
toGG <- matrix(ncol=ncol(l_dist[[1]]), nrow=0) %>% data.frame() %>%
	`colnames<-`(colnames(l_dist[[1]])) %>% 
	dplyr::mutate(exp=factor()) 

for (bedName in names(l_dist)){
	bed <- l_dist[[bedName]] %>%
	dplyr::mutate(exp=bedName)

	toGG <- rbind(toGG,bed)
}

toGG <- toGG %>% as_tibble() %>%
	mutate(
		state=factor(state), 
		group=factor(group),
		exp=gsub("_log2Ratio.*","",exp)) %>% 
	mutate(
		exp=factor(exp, 
			levels=c("SMC1_siNipbl","SA2_siNipbl", "SA1_siNipbl"))
		)

## add state annotations
anno <- read.table(file.path(wd,"state_annotations_simplified.txt"), 
	header=FALSE, sep="\t") %>% 
	`names<-`(c("state","anno","RGB")) %>%
	dplyr::mutate_at("state", as.factor) %>% 
	dplyr::mutate(anno=as.factor(anno)) %>%
	as_tibble()

toGG <- dplyr::inner_join(toGG, anno, by=c("state"="state")) %>% as_tibble()

summary(toGG)

## ================= PLOT ================= ##
## Count number of peaks per experiment
exp_labeller <- toGG %>% dplyr::group_by(exp) %>% dplyr::summarize(n=n()) %>%
	pull(n)  %>%
	paste0(levels(toGG$exp), "\n(n=", ., ")") %>% 
	gsub("[_]"," ",.) %>% `names<-`(levels(toGG$exp))

## Per experiment Relative distance
x_labels <- toGG %>% dplyr::group_by(exp) %>% dplyr::summarize(n=n()) %>%
	pull(n)  %>%
	paste0(levels(toGG$exp), "\n(n=", ., ")") %>% 
	gsub("[_]"," ",.) %>% `names<-`(levels(toGG$exp))


## plot  distance to TAD centre relative to TAF length, already computed in toGG

NGROUPS <- 10
EXPS <- c("SMC1_siNipbl","SA2_siNipbl","SA1_siNipbl")

p <- ggplot(toGG %>% dplyr::filter(exp %in% EXPS), aes(x=group, y=RelToMid)) +
  stat_boxplot(aes(x=group, y=RelToMid), 
    geom='errorbar', linetype=1, width=0.5) +
  geom_boxplot(notch=TRUE, aes(fill=group), alpha=.7,
    outlier.size=0, colour="gray9", size=.5) +
  scale_fill_manual(
      values= RColorBrewer::brewer.pal(NGROUPS,"RdBu"),
      breaks=factor(1:NGROUPS),
      labels=NULL,
      name=NULL) +
  scale_colour_manual(
      values= RColorBrewer::brewer.pal(NGROUPS,"RdBu"),
      breaks=factor(1:NGROUPS),
      limits=factor(1:NGROUPS),
      name="Log2Ratio in siRNA",
      labels=c("+++",rep("",NGROUPS-2),"---")) +
  stat_summary(fun=mean, geom="point", size=1) +
  theme(legend.position='none') +
  facet_wrap(~exp, nrow=2, labeller=labeller(exp=exp_labeller)) +
  guides(colour=FALSE, fill=FALSE)

p + 
  geom_smooth(mapping=aes(x=as.numeric(group), y = RelToMid),
    level=0.99,
    color="grey15",
    linetype="solid",
    size=.6) +
  theme_bw() +
  theme(panel.grid=element_blank()) + 
  scale_x_discrete(
    name="",
    breaks=1:10,
    labels=c("+++",rep("",NGROUPS-2),"---")) +
  theme(axis.text.x=element_text(angle=90, vjust=0.5)) + 
  scale_y_continuous(lim=c(0,1.07), 
    breaks=seq(0,1,0.25),
    labels=c("centre", "", "50%\ncentre", "", "border")) +
  facet_grid(~exp, labeller=labeller(exp=exp_labeller)) +
  ggtitle("Relative Distance to TAD centre\nin Log2 Ratio classified peaks") +
  theme(plot.title=element_text(hjust=0.5)) +
  labs(x="", y="Relative distance to TAD centre") + 
  facet_wrap(~exp, nrow=1, labeller=labeller(exp=exp_labeller)) +
  guides(fill="none", color="none")

getwd()
  ggsave("RelToMid_10groups_boxplot.pdf", height=8, width=6)


